# backend
- type: web
  name: backend-reportes
  runtime: node
  rootDir: backend
  buildCommand: npm install
  startCommand: node server.js

# frontend  
- type: static
  name: frontend-reportes
  rootDir: frontend
  buildCommand: npm run build
  publishPath: ./dist