services:
  - type: web
    name: backend-reportes-ia
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 18.18.0
      - key: GEMINI_API_KEY
        sync: false